"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useEffectEvent,
  useMemo,
  useRef,
  useState,
} from "react";
import type { Song, RepeatMode } from "@/lib/types";
import { readStorage, writeStorage, STORAGE_KEYS } from "@/lib/storage";
import { useSongs } from "@/context/SongsContext";
import { useDownloads } from "@/context/DownloadsContext";
import { getRelatedSection } from "@/lib/related";

type PersistedPlayerState = {
  queueIds: string[];
  currentId: string | null;
  position: number;
  volume: number;
  muted: boolean;
  shuffle: boolean;
  repeat: RepeatMode;
  autoplay?: boolean;
  // Without this, reloading while the full player view was open silently
  // collapsed it — the queue/song/position all restored correctly underneath,
  // but landing back on whatever page was open read as "it kicked me out of
  // the song" since nothing showed it was still playing.
  isExpanded?: boolean;
};

type PlaybackErrorInfo = { songId: string; message: string } | null;

type PlayerContextValue = {
  queue: Song[];
  currentSong: Song | null;
  currentIndex: number;
  isPlaying: boolean;
  isLoading: boolean;
  position: number;
  duration: number;
  volume: number;
  muted: boolean;
  shuffle: boolean;
  repeat: RepeatMode;
  error: PlaybackErrorInfo;
  history: string[];
  playCounts: Record<string, number>;
  isExpanded: boolean;
  setExpanded: (v: boolean) => void;
  analyser: AnalyserNode | null;
  audioGraphUnavailable: boolean;
  autoplay: boolean;
  setAutoplay: (v: boolean) => void;
  queueIsAutoGenerated: boolean;
  autoplayNotice: string | null;

  playSong: (song: Song, newQueue?: Song[]) => void;
  playQueueAt: (queueSongs: Song[], startIndex: number) => void;
  togglePlay: () => void;
  next: () => void;
  previous: () => void;
  seek: (time: number) => void;
  setVolume: (v: number) => void;
  toggleMute: () => void;
  toggleShuffle: () => void;
  cycleRepeat: () => void;
  addToQueue: (song: Song) => void;
  playNext: (song: Song) => void;
  removeFromQueue: (songId: string) => void;
  reorderQueue: (fromIndex: number, toIndex: number) => void;
  clearQueue: () => void;
  replaceQueue: (songs: Song[]) => void;
};

const PlayerContext = createContext<PlayerContextValue | null>(null);

const MAX_HISTORY = 30;
const POSITION_SAVE_INTERVAL_MS = 4000;

export function PlayerProvider({ children }: { children: React.ReactNode }) {
  const { getSongById, getAllSongs, getSongsByAlbum } = useSongs();
  const { getOfflineBlobUrl } = useDownloads();
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const hydrated = useRef(false);
  const lastPositionSave = useRef(0);
  const recentlyPlayedRef = useRef<string[]>([]);
  const audioContextRef = useRef<AudioContext | null>(null);
  const sourceNodeRef = useRef<MediaElementAudioSourceNode | null>(null);
  // Only the very first source-load after hydrating a persisted session
  // should resume mid-track. Every other song change (next/previous/ended/
  // manual pick, even re-selecting an already-played song) must start at 0 —
  // consumed once then cleared, so it never leaks into later songs.
  const resumePositionOnLoad = useRef<number | null>(null);
  const [analyser, setAnalyser] = useState<AnalyserNode | null>(null);
  const [audioGraphUnavailable, setAudioGraphUnavailable] = useState(false);

  const [queue, setQueue] = useState<Song[]>([]);
  const [currentId, setCurrentId] = useState<string | null>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [position, setPosition] = useState(0);
  const [duration, setDuration] = useState(0);
  const [volume, setVolumeState] = useState(0.8);
  const [muted, setMuted] = useState(false);
  const [shuffle, setShuffle] = useState(false);
  const [repeat, setRepeat] = useState<RepeatMode>("off");
  const [error, setError] = useState<PlaybackErrorInfo>(null);
  const [history, setHistory] = useState<string[]>([]);
  const [playCounts, setPlayCounts] = useState<Record<string, number>>({});
  const [isExpanded, setExpanded] = useState(false);
  const [autoplay, setAutoplay] = useState(true);
  const [queueIsAutoGenerated, setQueueIsAutoGenerated] = useState(false);
  const [autoplayNotice, setAutoplayNotice] = useState<string | null>(null);
  const autoplayNoticeTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  const currentIndex = useMemo(
    () => queue.findIndex((s) => s.id === currentId),
    [queue, currentId]
  );
  const currentSong = currentIndex >= 0 ? queue[currentIndex] : null;

  // Keep queue entries in sync with admin edits (title/cover/metadata) —
  // `getSongById`'s identity changes whenever the songs context's overrides
  // change, so this re-runs exactly when a song gets edited elsewhere.
  useEffect(() => {
    if (!hydrated.current) return;
    setQueue((prev) => {
      let changed = false;
      const next = prev.map((s) => {
        const fresh = getSongById(s.id);
        if (fresh && fresh !== s) {
          changed = true;
          return fresh;
        }
        return s;
      });
      return changed ? next : prev;
    });
  }, [getSongById]);

  // --- create the single persistent <audio> element once ---
  useEffect(() => {
    const audio = new Audio();
    audio.preload = "metadata";
    // Needed so a future external audio source can still be analyzed by the
    // visualizer if that host sends CORS headers — same-origin local files
    // are unaffected either way.
    audio.crossOrigin = "anonymous";
    audioRef.current = audio;
    return () => {
      audio.pause();
      audio.src = "";
      audioRef.current = null;
      sourceNodeRef.current?.disconnect();
      audioContextRef.current?.close().catch(() => {});
      audioContextRef.current = null;
      sourceNodeRef.current = null;
      if (autoplayNoticeTimeout.current) clearTimeout(autoplayNoticeTimeout.current);
    };
  }, []);

  // Lazily builds the Web Audio graph (AudioContext → MediaElementSource →
  // AnalyserNode → destination) on first user-gesture playback, per the
  // browser autoplay policy. Only ever runs once per audio element — a
  // MediaElementAudioSourceNode can't be created twice from the same
  // <audio>, which is also why this app only ever has one <audio> element.
  const ensureAudioGraph = useCallback(() => {
    const audio = audioRef.current;
    if (!audio) return;
    if (audioContextRef.current) {
      if (audioContextRef.current.state === "suspended") {
        audioContextRef.current.resume().catch(() => {});
      }
      return;
    }
    try {
      const AudioContextCtor = window.AudioContext ?? (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
      if (!AudioContextCtor) {
        setAudioGraphUnavailable(true);
        return;
      }
      const ctx = new AudioContextCtor();
      const source = ctx.createMediaElementSource(audio);
      const node = ctx.createAnalyser();
      node.fftSize = 256;
      node.smoothingTimeConstant = 0.8;
      source.connect(node);
      node.connect(ctx.destination);
      audioContextRef.current = ctx;
      sourceNodeRef.current = source;
      setAnalyser(node);
    } catch {
      // Some environments (older Safari, restrictive privacy modes) can
      // throw here — fall back to the decorative animation instead of
      // breaking playback.
      setAudioGraphUnavailable(true);
    }
  }, []);

  // --- hydrate from localStorage on mount ---
  useEffect(() => {
    const saved = readStorage<PersistedPlayerState | null>(STORAGE_KEYS.playerState, null);
    setHistory(readStorage<string[]>(STORAGE_KEYS.history, []));
    setPlayCounts(readStorage<Record<string, number>>(STORAGE_KEYS.playCounts, {}));

    if (saved) {
      const restoredQueue = saved.queueIds
        .map((id) => getSongById(id))
        .filter((s): s is Song => !!s);
      setQueue(restoredQueue);
      if (saved.currentId && restoredQueue.some((s) => s.id === saved.currentId)) {
        setCurrentId(saved.currentId);
        setPosition(saved.position ?? 0);
        resumePositionOnLoad.current = saved.position ?? 0;
      }
      setVolumeState(saved.volume ?? 0.8);
      setMuted(saved.muted ?? false);
      setShuffle(saved.shuffle ?? false);
      setRepeat(saved.repeat ?? "off");
      setAutoplay(saved.autoplay ?? true);
      if (saved.isExpanded && saved.currentId && restoredQueue.some((s) => s.id === saved.currentId)) {
        setExpanded(true);
      }
    }
    hydrated.current = true;
    // Mount-only by design: resolves persisted IDs with whatever song data is
    // available at first render. The queue-refresh effect above keeps things
    // in sync afterwards, so re-running this on every edit isn't needed.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // --- persist lightweight player state (queue/settings write immediately,
  // position is throttled since timeupdate fires several times a second) ---
  useEffect(() => {
    if (!hydrated.current) return;
    const payload: PersistedPlayerState = {
      queueIds: queue.map((s) => s.id),
      currentId,
      position,
      volume,
      muted,
      shuffle,
      repeat,
      autoplay,
      isExpanded,
    };
    writeStorage(STORAGE_KEYS.playerState, payload);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [queue, currentId, volume, muted, shuffle, repeat, autoplay, isExpanded]);

  useEffect(() => {
    if (!hydrated.current) return;
    const now = Date.now();
    if (now - lastPositionSave.current < POSITION_SAVE_INTERVAL_MS) return;
    lastPositionSave.current = now;
    const payload: PersistedPlayerState = {
      queueIds: queue.map((s) => s.id),
      currentId,
      position,
      volume,
      muted,
      shuffle,
      repeat,
      autoplay,
      isExpanded,
    };
    writeStorage(STORAGE_KEYS.playerState, payload);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [position]);

  const recordPlay = useCallback((songId: string) => {
    setHistory((prev) => {
      const next = [songId, ...prev.filter((id) => id !== songId)].slice(0, MAX_HISTORY);
      writeStorage(STORAGE_KEYS.history, next);
      return next;
    });
    setPlayCounts((prev) => {
      const next = { ...prev, [songId]: (prev[songId] ?? 0) + 1 };
      writeStorage(STORAGE_KEYS.playCounts, next);
      return next;
    });
    recentlyPlayedRef.current = [songId, ...recentlyPlayedRef.current].slice(0, 8);
  }, []);

  // --- load a new source whenever the current song changes ---
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;

    if (!currentSong) {
      audio.pause();
      audio.removeAttribute("src");
      return;
    }

    const source = currentSong.audioSources.find((s) => s.type === "local") ?? currentSong.audioSources[0];
    if (!source) {
      setError({ songId: currentSong.id, message: "No hay una fuente de audio disponible para esta canción." });
      setIsPlaying(false);
      return;
    }

    setError(null);
    setIsLoading(true);

    let cancelled = false;
    (async () => {
      // A song downloaded via "Mis descargas" plays from its locally-stored
      // Blob instead of the network URL — that's the whole point of
      // downloading it: no request to the server at all, so it keeps
      // working offline instead of just being cached-and-hopefully-still-there.
      const offlineUrl = await getOfflineBlobUrl(currentSong.id).catch(() => null);
      if (cancelled) return;
      const effectiveUrl = offlineUrl ?? source.url;

      if (!audio.src.endsWith(effectiveUrl) && audio.src !== effectiveUrl) {
        // Consume the one-shot resume position (only set right after hydrating
        // a persisted session) — every other transition starts fresh. Gating
        // on `!audio.src` too (not just the ref) means a resume can only ever
        // apply to the very first source this <audio> element ever loads —
        // if this component were ever remounted mid-session (e.g. a dev-mode
        // Fast Refresh) the ref would come back, but the audio element already
        // having a src proves a song was already playing, so a normal song
        // switch can never be mistaken for "resume where the app was reloaded".
        const isFirstLoadEver = !audio.src;
        const resumeAt = isFirstLoadEver ? resumePositionOnLoad.current : null;
        resumePositionOnLoad.current = null;
        audio.pause();
        setDuration(0);
        audio.src = effectiveUrl;
        audio.load();
        if (resumeAt && resumeAt > 0) {
          const onceLoaded = () => {
            audio.currentTime = resumeAt;
            setPosition(resumeAt);
            audio.removeEventListener("loadedmetadata", onceLoaded);
          };
          audio.addEventListener("loadedmetadata", onceLoaded);
        } else {
          audio.currentTime = 0;
          setPosition(0);
        }
      }

      if (isPlaying) {
        audio.play().catch(() => {
          // autoplay was blocked or the source failed — surface a paused state, not a crash
          setIsPlaying(false);
        });
      }
    })();

    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentSong?.id, getOfflineBlobUrl]);

  // --- navigation helpers ---
  const pickNextShuffled = useCallback(
    (excludeCurrent: boolean) => {
      if (queue.length === 0) return null;
      const recent = recentlyPlayedRef.current;
      let candidates = queue.filter((s) => (!excludeCurrent || s.id !== currentId) && !recent.includes(s.id));
      if (candidates.length === 0) {
        candidates = queue.filter((s) => !excludeCurrent || s.id !== currentId);
      }
      if (candidates.length === 0) candidates = queue;
      return candidates[Math.floor(Math.random() * candidates.length)];
    },
    [queue, currentId]
  );

  // Builds a small run of "what to play next" suggestions when the queue
  // runs out, reusing the same priority logic as the related-songs panel
  // (same artist → same era → tags/genre → general mix) so autoplay and the
  // "Relacionadas" tab never disagree about what counts as related.
  const buildAutoplaySuggestions = useCallback(
    (fromSong: Song, excludeIds: Set<string>) => {
      const pool = getAllSongs().filter((s) => s.includeInMixes !== false && !excludeIds.has(s.id));
      if (pool.length === 0) return [];
      const { songs } = getRelatedSection(fromSong, pool);
      return songs.slice(0, 5);
    },
    [getAllSongs]
  );

  const showAutoplayNotice = useCallback((message: string) => {
    setAutoplayNotice(message);
    if (autoplayNoticeTimeout.current) clearTimeout(autoplayNoticeTimeout.current);
    autoplayNoticeTimeout.current = setTimeout(() => setAutoplayNotice(null), 3200);
  }, []);

  const next = useCallback(() => {
    if (queue.length === 0) return;
    if (shuffle) {
      const song = pickNextShuffled(true);
      if (song) {
        setCurrentId(song.id);
        setIsPlaying(true);
      }
      return;
    }
    const idx = currentIndex;
    if (idx === -1) return;
    if (idx === queue.length - 1) {
      if (repeat === "all") {
        setCurrentId(queue[0].id);
        setIsPlaying(true);
        return;
      }
      const endingSong = queue[idx];
      if (autoplay && endingSong) {
        const excludeIds = new Set([...queue.map((s) => s.id), ...recentlyPlayedRef.current]);
        const suggestions = buildAutoplaySuggestions(endingSong, excludeIds);
        if (suggestions.length > 0) {
          setQueue((prev) => [...prev, ...suggestions]);
          setQueueIsAutoGenerated(true);
          setCurrentId(suggestions[0].id);
          setIsPlaying(true);
          showAutoplayNotice("Se añadieron canciones sugeridas a tu cola.");
          return;
        }
      }
      setIsPlaying(false);
      return;
    }
    setCurrentId(queue[idx + 1].id);
    setIsPlaying(true);
  }, [queue, shuffle, currentIndex, repeat, pickNextShuffled, autoplay, buildAutoplaySuggestions, showAutoplayNotice]);

  const previous = useCallback(() => {
    const audio = audioRef.current;
    if (audio && audio.currentTime > 3) {
      audio.currentTime = 0;
      setPosition(0);
      return;
    }
    if (queue.length === 0) return;
    if (shuffle) {
      const song = pickNextShuffled(true);
      if (song) {
        setCurrentId(song.id);
        setIsPlaying(true);
      }
      return;
    }
    const idx = currentIndex;
    if (idx <= 0) {
      if (repeat === "all") {
        setCurrentId(queue[queue.length - 1].id);
        setIsPlaying(true);
      } else if (audio) {
        audio.currentTime = 0;
        setPosition(0);
      }
      return;
    }
    setCurrentId(queue[idx - 1].id);
    setIsPlaying(true);
  }, [queue, shuffle, currentIndex, repeat, pickNextShuffled]);

  // Non-reactive "latest callback" for the native `ended` event — always sees
  // fresh repeat/next without needing to be in the audio-events effect's deps.
  const handleEnded = useEffectEvent(() => {
    const audio = audioRef.current;
    if (repeat === "one" && audio) {
      audio.currentTime = 0;
      audio.play().catch(() => setIsPlaying(false));
      return;
    }
    // "Reproducción automática" off means exactly that: nothing plays on its
    // own once the current song ends, queue or no queue. The manual
    // "Siguiente" button still calls next() directly (a different code
    // path from this natural-end handler), so it's unaffected by this check.
    if (!autoplay) {
      setIsPlaying(false);
      return;
    }
    next();
  });

  // --- wire native audio events once ---
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;

    const onTimeUpdate = () => setPosition(audio.currentTime);
    const onDurationChange = () => setDuration(audio.duration || 0);
    const onLoadedMetadata = () => {
      setDuration(audio.duration || 0);
      setIsLoading(false);
    };
    const onPlay = () => {
      setIsPlaying(true);
      if (currentSong) recordPlay(currentSong.id);
    };
    const onPause = () => setIsPlaying(false);
    const onWaiting = () => setIsLoading(true);
    const onCanPlay = () => setIsLoading(false);
    const onError = () => {
      setIsLoading(false);
      setIsPlaying(false);
      if (currentSong) {
        setError({ songId: currentSong.id, message: "No se pudo reproducir este archivo." });
      }
    };
    const onEnded = () => handleEnded();

    audio.addEventListener("timeupdate", onTimeUpdate);
    audio.addEventListener("durationchange", onDurationChange);
    audio.addEventListener("loadedmetadata", onLoadedMetadata);
    audio.addEventListener("play", onPlay);
    audio.addEventListener("pause", onPause);
    audio.addEventListener("waiting", onWaiting);
    audio.addEventListener("canplay", onCanPlay);
    audio.addEventListener("error", onError);
    audio.addEventListener("ended", onEnded);

    return () => {
      audio.removeEventListener("timeupdate", onTimeUpdate);
      audio.removeEventListener("durationchange", onDurationChange);
      audio.removeEventListener("loadedmetadata", onLoadedMetadata);
      audio.removeEventListener("play", onPlay);
      audio.removeEventListener("pause", onPause);
      audio.removeEventListener("waiting", onWaiting);
      audio.removeEventListener("canplay", onCanPlay);
      audio.removeEventListener("error", onError);
      audio.removeEventListener("ended", onEnded);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentSong?.id, recordPlay]);

  // --- Media Session API ---
  useEffect(() => {
    if (typeof window === "undefined" || !("mediaSession" in navigator)) return;
    if (!currentSong) {
      navigator.mediaSession.metadata = null;
      return;
    }
    const cover = currentSong.coverUrl;
    navigator.mediaSession.metadata = new MediaMetadata({
      title: currentSong.title,
      artist: currentSong.alias ?? currentSong.artist,
      album: currentSong.albumId ?? undefined,
      artwork: cover
        ? [
            { src: cover, sizes: "512x512", type: "image/png" },
          ]
        : [],
    });
    navigator.mediaSession.setActionHandler("play", () => audioRef.current?.play());
    navigator.mediaSession.setActionHandler("pause", () => audioRef.current?.pause());
    navigator.mediaSession.setActionHandler("previoustrack", () => previous());
    navigator.mediaSession.setActionHandler("nexttrack", () => next());
    navigator.mediaSession.setActionHandler("seekto", (details) => {
      if (details.seekTime != null && audioRef.current) {
        audioRef.current.currentTime = details.seekTime;
      }
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentSong?.id, previous, next]);

  useEffect(() => {
    if (typeof window === "undefined" || !("mediaSession" in navigator)) return;
    navigator.mediaSession.playbackState = isPlaying ? "playing" : "paused";
  }, [isPlaying]);

  // --- volume / mute ---
  useEffect(() => {
    const audio = audioRef.current;
    if (!audio) return;
    audio.volume = volume;
    audio.muted = muted;
  }, [volume, muted]);

  // --- public actions ---
  const playQueueAt = useCallback(
    (queueSongs: Song[], startIndex: number) => {
      ensureAudioGraph();
      const target = queueSongs[startIndex];
      if (!target) return;
      if (autoplay && queueSongs.length === 1) {
        const suggestions = buildAutoplaySuggestions(target, new Set([target.id]));
        if (suggestions.length > 0) {
          setQueue([target, ...suggestions]);
          setQueueIsAutoGenerated(true);
        } else {
          setQueue(queueSongs);
          setQueueIsAutoGenerated(false);
        }
      } else {
        setQueue(queueSongs);
        setQueueIsAutoGenerated(false);
      }
      setPosition(0);
      setCurrentId(target.id);
      setIsPlaying(true);
    },
    [ensureAudioGraph, autoplay, buildAutoplaySuggestions]
  );

  const playSong = useCallback(
    (song: Song, newQueue?: Song[]) => {
      ensureAudioGraph();
      if (newQueue) {
        const idx = newQueue.findIndex((s) => s.id === song.id);
        playQueueAt(newQueue, idx >= 0 ? idx : 0);
        return;
      }
      // Called with no explicit queue — e.g. the "Reproducir" button on a
      // song's own detail page, which has no natural list context. Without
      // building one here, that song played entirely alone: nothing queued
      // after it, so "reproducción automática" had nothing to advance to
      // even though the switch was on. Album tracks get their album's real
      // running order; a single gets an auto-generated related/random set,
      // same pool the end-of-queue autoplay uses.
      if (song.albumId) {
        const albumTracks = getSongsByAlbum(song.albumId);
        if (albumTracks.length > 1) {
          playQueueAt(albumTracks, albumTracks.findIndex((s) => s.id === song.id));
          return;
        }
      }
      const suggestions = buildAutoplaySuggestions(song, new Set([song.id]));
      if (suggestions.length > 0) {
        const builtQueue = [song, ...suggestions];
        setQueue(builtQueue);
        setQueueIsAutoGenerated(true);
        setPosition(0);
        setCurrentId(song.id);
        setIsPlaying(true);
        return;
      }
      setQueue((prev) => {
        if (prev.some((s) => s.id === song.id)) return prev;
        return [...prev, song];
      });
      setQueueIsAutoGenerated(false);
      setPosition(0);
      setCurrentId(song.id);
      setIsPlaying(true);
    },
    [playQueueAt, ensureAudioGraph, getSongsByAlbum, buildAutoplaySuggestions]
  );

  const togglePlay = useCallback(() => {
    const audio = audioRef.current;
    if (!audio || !currentSong) return;
    if (isPlaying) {
      audio.pause();
    } else {
      ensureAudioGraph();
      audio.play().catch(() => setIsPlaying(false));
    }
  }, [isPlaying, currentSong, ensureAudioGraph]);

  const seek = useCallback((time: number) => {
    const audio = audioRef.current;
    if (!audio) return;
    audio.currentTime = time;
    setPosition(time);
  }, []);

  const setVolume = useCallback((v: number) => {
    setVolumeState(Math.min(1, Math.max(0, v)));
    setMuted(false);
  }, []);

  const toggleMute = useCallback(() => setMuted((m) => !m), []);
  const toggleShuffle = useCallback(() => setShuffle((s) => !s), []);
  const cycleRepeat = useCallback(() => {
    setRepeat((r) => (r === "off" ? "all" : r === "all" ? "one" : "off"));
  }, []);

  const addToQueue = useCallback((song: Song) => {
    setQueue((prev) => (prev.some((s) => s.id === song.id) ? prev : [...prev, song]));
    setQueueIsAutoGenerated(false);
  }, []);

  const playNext = useCallback(
    (song: Song) => {
      setQueue((prev) => {
        const withoutSong = prev.filter((s) => s.id !== song.id);
        const idx = withoutSong.findIndex((s) => s.id === currentId);
        const insertAt = idx >= 0 ? idx + 1 : withoutSong.length;
        return [...withoutSong.slice(0, insertAt), song, ...withoutSong.slice(insertAt)];
      });
      setQueueIsAutoGenerated(false);
    },
    [currentId]
  );

  const removeFromQueue = useCallback(
    (songId: string) => {
      setQueue((prev) => prev.filter((s) => s.id !== songId));
      if (songId === currentId) {
        setIsPlaying(false);
      }
    },
    [currentId]
  );

  const reorderQueue = useCallback((fromIndex: number, toIndex: number) => {
    setQueue((prev) => {
      const next = [...prev];
      const [moved] = next.splice(fromIndex, 1);
      next.splice(toIndex, 0, moved);
      return next;
    });
  }, []);

  const clearQueue = useCallback(() => {
    setQueue([]);
    setCurrentId(null);
    setIsPlaying(false);
    setQueueIsAutoGenerated(false);
  }, []);

  const replaceQueue = useCallback((songsList: Song[]) => {
    setQueue(songsList);
    setQueueIsAutoGenerated(false);
  }, []);

  const value: PlayerContextValue = {
    queue,
    currentSong,
    currentIndex,
    isPlaying,
    isLoading,
    position,
    duration,
    volume,
    muted,
    shuffle,
    repeat,
    error,
    history,
    playCounts,
    isExpanded,
    setExpanded,
    analyser,
    audioGraphUnavailable,
    autoplay,
    setAutoplay,
    queueIsAutoGenerated,
    autoplayNotice,
    playSong,
    playQueueAt,
    togglePlay,
    next,
    previous,
    seek,
    setVolume,
    toggleMute,
    toggleShuffle,
    cycleRepeat,
    addToQueue,
    playNext,
    removeFromQueue,
    reorderQueue,
    clearQueue,
    replaceQueue,
  };

  return <PlayerContext.Provider value={value}>{children}</PlayerContext.Provider>;
}

export function usePlayer() {
  const ctx = useContext(PlayerContext);
  if (!ctx) throw new Error("usePlayer must be used within PlayerProvider");
  return ctx;
}
