"use client";

import { ChevronUp, ListMusic } from "lucide-react";
import { usePlayer } from "@/context/PlayerContext";
import CoverImage from "@/components/media/CoverImage";

export default function NextTrackPreview({ onOpen }: { onOpen: () => void }) {
  const { queue, currentIndex, queueIsAutoGenerated } = usePlayer();
  const nextSong = currentIndex >= 0 ? queue[currentIndex + 1] : undefined;

  if (!nextSong) return null;

  return (
    <button
      type="button"
      onClick={onOpen}
      aria-label={`Abrir siguientes y sugerencias. Próxima canción: ${nextSong.title}`}
      className="group mx-3 mb-2.5 flex shrink-0 items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.07] p-2.5 text-left shadow-lg backdrop-blur-xl transition-colors hover:bg-white/[0.12] lg:hidden"
    >
      <div className="h-11 w-11 shrink-0 overflow-hidden rounded-lg">
        <CoverImage src={nextSong.coverUrl} title={nextSong.title} size="xs" />
      </div>
      <span className="min-w-0 flex-1">
        <span className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.16em] text-accent">
          <ListMusic className="h-3.5 w-3.5" /> A continuación
        </span>
        <span className="mt-0.5 block truncate text-sm font-semibold text-foreground">{nextSong.title}</span>
        <span className="block truncate text-xs text-foreground-muted">
          {nextSong.alias ?? nextSong.artist} · {queueIsAutoGenerated ? "Sugerencia para tu mix" : "En tu cola"}
        </span>
      </span>
      <span className="flex shrink-0 flex-col items-center gap-0.5 px-1 text-[10px] font-medium text-foreground-muted group-hover:text-foreground">
        <ChevronUp className="h-4 w-4" />
        Ver más
      </span>
    </button>
  );
}
