"use client";

import { ListMusic, Text, Sparkles, MessageSquare, X } from "lucide-react";
import clsx from "clsx";
import type { Song, Album } from "@/lib/types";
import { usePlayer } from "@/context/PlayerContext";
import QueueTab from "./panels/QueueTab";
import LyricsTab from "./panels/LyricsTab";
import RelatedTab from "./panels/RelatedTab";
import CommentsTab from "./panels/CommentsTab";

export type SidePanelTab = "queue" | "lyrics" | "related" | "comments";

const TABS: { key: SidePanelTab; label: string; icon: typeof ListMusic }[] = [
  { key: "queue", label: "A continuación", icon: ListMusic },
  { key: "lyrics", label: "Letra", icon: Text },
  { key: "related", label: "Relacionadas", icon: Sparkles },
  { key: "comments", label: "Comentarios", icon: MessageSquare },
];

export default function SidePanel({
  tab,
  onTabChange,
  onClose,
  song,
  album,
  albumTracks,
  related,
  relatedTitle,
}: {
  tab: SidePanelTab;
  onTabChange: (tab: SidePanelTab) => void;
  onClose?: () => void;
  song: Song;
  album?: Album;
  albumTracks: Song[];
  related: Song[];
  relatedTitle?: string;
}) {
  const { queueIsAutoGenerated } = usePlayer();

  return (
    <div className="flex h-full flex-col">
      <div className="flex shrink-0 items-center justify-between border-b border-border pl-1 pr-2">
        <div className="no-scrollbar flex items-center gap-1 overflow-x-auto">
          {TABS.map((t) => (
            <button
              key={t.key}
              type="button"
              onClick={() => onTabChange(t.key)}
              className={clsx(
                "flex shrink-0 items-center gap-1.5 border-b-2 px-3 py-2.5 text-xs font-medium transition-colors",
                tab === t.key
                  ? "border-accent text-foreground"
                  : "border-transparent text-foreground-muted hover:text-foreground"
              )}
            >
              <t.icon className="h-3.5 w-3.5" />
              {t.key === "queue" && queueIsAutoGenerated ? "Tu mix" : t.label}
            </button>
          ))}
        </div>
        {onClose && (
          <button
            type="button"
            onClick={onClose}
            aria-label="Cerrar panel"
            className="shrink-0 rounded-full p-1.5 text-foreground-muted hover:bg-surface-hover hover:text-foreground lg:hidden"
          >
            <X className="h-4 w-4" />
          </button>
        )}
      </div>

      <div className="min-h-0 flex-1">
        {tab === "queue" && <QueueTab />}
        {tab === "lyrics" && <LyricsTab song={song} />}
        {tab === "related" && (
          <RelatedTab song={song} album={album} albumTracks={albumTracks} related={related} relatedTitle={relatedTitle} />
        )}
        {tab === "comments" && <CommentsTab song={song} />}
      </div>
    </div>
  );
}
