import type { Album } from "@/lib/types";
import { importedAlbums } from "./imported.generated";

// Real catalog only — generated by scripts/import-music.mjs from /musica.
export const albums: Album[] = [...importedAlbums];
